### ISSUE TITLE
WASM build?

### ISSUE THREAD

**Issue by elalish** [hannobraun/3mf-rs#20]
I heard rumors that Rust makes it easy to compile into WASM. I'd love to use a library like this on the web. Does anyone know how much work that would take?

**Comment by hannobraun** [comment]
This library is used in [Fornjot](https://github.com/hannobraun/Fornjot), specifically the [`fj-export`](https://github.com/hannobraun/Fornjot/tree/main/crates/fj-export) crate. While Fornjot doesn't run in browsers yet, that is a goal. In preparation of that goal, a subset of Fornjot is being compiled to the `wasm32-unknown-unknown` target as part of its regular CI build. The `fj-export` crate, and thus `3mf-rs` also, are among that subset.

So it compiles to WASM, but would it work? Having taken a look at the code just now, I'm a bit confused about that. `3mf-rs` [uses `std::fs::File`](https://github.com/hannobraun/3mf-rs/blob/ffad048d093559c1db2b1d12a07c499c6d9be982/src/write.rs#L15), and I don't think that would be available on the web? I don't know how that all works. I would have expected that to just not compile, but maybe it will cause an error at runtime.

The good news is, there's really no reason for `3mf-rs` to use `File` in the first place. The `write` method (where `File` is used) accepts a `Path` as a parameter and opens the file at that path. I don't think this is appropriate for a library like this. What it should do instead, is accept an `impl io::Write` instead of the `Path`. Then it would work everywhere, and the caller could decide whether the 3MF should be written into a file, and in-memory buffer, or whatever else.

A pull request making that change would be very welcome! I will probably do it myself, as soon as I get serious about browser support in Fornjot. But given my workload, this might take a long time.

---

On top of that, some extra work might be required, depending on what you mean by "use it on the web". Do you intend to write a WASM-based Rust application that runs in the browser? Then using 3MF would take no work on top of the rather simple change I already mentioned. Just add it to `Cargo.toml` like any other Rust dependency.

If you want to use this library from JavaScript, that's a different matter. You would have to create bindings using [`wasm-bindgen`](https://crates.io/crates/wasm-bindgen) or something like it. I don't think that would be very difficult either, but I'm not sure what specifically would be involved. The [Rust and WebAssembly](https://rustwasm.github.io/docs/book/) book should have all the relevant information though.

**Comment by hannobraun** [comment]
I've opened #21 to track the improvement I've suggested here. Closing this issue, as I believe I've answered the question, but feel free to post more comments here, @elalish!

**Comment by elalish** [comment]
Thanks for the detailed response! SG, but yes, I think I'd be looking for wasm bindings. I've already built these for my own C++ project, Manifold, but I haven't written any Rust (yet). I actually wrote most of the 3MF spec back in the day, and it seems like a natural output format for [manifoldcad.org](https://manifoldcad.org/). Was hoping by now there would be an open-source web library for it, but yours is the closest I've found.

**Comment by hannobraun** [comment]
Wow, both Manifold and 3MF are very impressive feats!

So, I haven't created WASM bindings for a Rust library yet, but I've done some experimentation with Rust *applications* in the browser. Based on that experience, I would guess that creating bindings for `3mf-rs` wouldn't be very difficult (as I said above), but of course there might be details I'm missing. And not having used Rust yet will introduce friction, and I expect that would probably be the main hurdle.

Even with #21 addressed, I think you would need a wrapper function around `write` in your bindings. `impl io::Write` would be an appropriate abstraction for a Rust caller, but I think JavaScript wouldn't know how to deal with that. Your wrapper could just accept a `&mut [u8]` slice instead. `wasm-bindgen` [seems to support that](https://rustwasm.github.io/docs/wasm-bindgen/reference/types/number-slices.html) (translating it into an appropriate `TypedArray`), and conveniently `&mut [u8]` also [implements `io::Write`](https://doc.rust-lang.org/std/io/trait.Write.html#impl-Write-for-%26mut%20%5Bu8%5D).

That leaves the question of what to do about the [data types](https://github.com/hannobraun/3mf-rs/blob/main/src/mesh.rs). I think maybe the most practical approach might be to construct those within your wrapper function, which could accept raw slices (`&[f64]`/`&[u32]`) as parameters  for the vertices and indices.

Hard to say more without diving in (which I don't really have time for). But if you decide to do this and run into trouble, always feel free to ask me questions!

**Comment by elalish** [comment]
Thanks! That all sounds reasonable. Not my highest priority, but I may eventually come back and help if I can't find anything more turn-key. Fornjot (how is that pronounced?) looks cool. Having spent a number of years writing a CAD kernel, I can say that's a significant undertaking. Can't wait to see what comes of it. If you get tired of writing your own mesh Boolean operations, feel free to use Manifold. I know, not Rust, but at the time I didn't know about it, plus I don't think Rust has the same level of CUDA GPU support (yet).

**Comment by hannobraun** [comment]
> Thanks! That all sounds reasonable. Not my highest priority, but I may eventually come back and help if I can't find anything more turn-key.

Understood. Let me know, in case you need help!


> Fornjot (how is that pronounced?) looks cool.

Thank you. Well, it's a name from Norse mythology and I'm not Norse, so what do I know :smile: 

[According to Wikipedia](https://en.wikipedia.org/wiki/Fornjot_(moon)) it's [/ˈfɔːrnjoʊt/](https://en.wikipedia.org/wiki/Help:IPA/English), so the 'j' sounds like the 'y' in "yes".


> Having spent a number of years writing a CAD kernel, I can say that's a significant undertaking. Can't wait to see what comes of it.

I've been at it for a few years myself (including various early prototypes), the last one full-time, so I know all about that. Still lots to do, but I'm optimistic that we'll get somewhere interesting!


> If you get tired of writing your own mesh Boolean operations, feel free to use Manifold.

Thanks, but I'm using boundary representation, so unfortunately Manifold's mesh-based approach doesn't apply.

**Comment by elalish** [comment]
Well, a mesh is definitely a boundary representation, but a simple one. I take it you're working on NURBS?

**Comment by hannobraun** [comment]
> Well, a mesh is definitely a boundary representation, but a simple one.

Yes, you could say that, but I don't think that's how the term is commonly used. [According to Wikipedia](https://en.wikipedia.org/wiki/Boundary_representation):
> A boundary representation of a model comprises [topological](https://en.wikipedia.org/wiki/Topology) components ([faces](https://en.wikipedia.org/wiki/Face_(geometry)), [edges](https://en.wikipedia.org/wiki/Edge_(geometry)) and [vertices](https://en.wikipedia.org/wiki/Vertex_(geometry))) and the connections between them, along with geometric definitions for those components (surfaces, curves and points, respectively)."

That's how I understand the term when I say that Fornjot uses b-rep.


> I take it you're working on NURBS?

I'd like that eventually, but not yet. For now, geometry is more limited.

To me, the important aspect of b-rep is to have the topological components available, so you can select those to perform operations on them. To chamfer an edge, for example.

**Comment by elalish** [comment]
That makes sense, though since I use a halfedge data structure internally, I'd say it meets those criteria. I haven't looked into edge and face selection and modification routines yet, but I'm certainly interested. Things like edge chamfer and face push/pull seem quite useful and implementable. I've even done some work on a smooth interpolator for triangle meshes, allowing them to act in place of larger surfaces. 

Anyway, if there's a chance you're interested in seeing what our powers combined can accomplish, I'm doing my best to pull together an open source geometry community around Manifold. I read your manifesto on Fornjot and I think we're very well aligned in our goals.

**Comment by hannobraun** [comment]
> That makes sense, though since I use a halfedge data structure internally, I'd say it meets those criteria. I haven't looked into edge and face selection and modification routines yet, but I'm certainly interested. Things like edge chamfer and face push/pull seem quite useful and implementable. I've even done some work on a smooth interpolator for triangle meshes, allowing them to act in place of larger surfaces.

Sounds promising!




> Anyway, if there's a chance you're interested in seeing what our powers combined can accomplish, I'm doing my best to pull together an open source geometry community around Manifold. I read your manifesto on Fornjot and I think we're very well aligned in our goals.

What do you mean, specifically? I'm always happy to connect with like-minded folks, and I'd love to talk some more, if you're interested. Maybe set up a call?

But if you're talking about joining forces and work together on Manifold, thank you, but no. First, I don't think I have it in me to work on anything non-trivial in C++. Second, I've taken some weird approaches in Fornjot, and I'd like to see where that leads. Third, I'm pretty sure, if I announced I was abandoning Fornjot and joining a non-Rust project, I'd lose most of my sponsors :smile:

**Comment by hannobraun** [comment]
> Okay, that's fair smile, just figured never hurts to ask. Even if our projects remain distinct, I'm excited to see more projects producing manifold geometry!

:+1: 


> I think Rust would be a great language for Manifold too now that I'm learning more about it. If Rust gets better GPGPU support it would be nice to switch over.

GPGPU is one of those aspects I've glossed over so far. I see the importance, but it would be yet another in an already long line of problems. Maybe by the time I'm ready to tackle this, [`rust-gpu`](https://github.com/EmbarkStudios/rust-gpu) will be a viable option.
